### ISSUE TITLE
get_description returns and incorrect row_range for unsorted datetime index data

### ISSUE THREAD

**Issue by DrNickClarke** [man-group/ArcticDB#1120]
### Describe the bug

It is possible to write data with an unsorted datetime index using validate_index=False.
If you write such data then lib.get_description on the symbol seems to have incorrect data, which looks like it is assuming the index is sorted.

### Steps/Code to Reproduce

```
arctic = adb.Arctic("lmdb://arcticdb_tests")
lib = arctic.get_library('get_desc', create_if_missing=True)
base3_df = pd.DataFrame(
    index=pd.DatetimeIndex(
        [datetime(2023, 11, 3), datetime(2023, 11, 1), datetime(2023, 11, 2)],
        name='date'
        ),
    data={'col': [3., 1., 2.]}
    )
sym3_unsorted = 'test_append3_unsorted'
lib.write(sym3_unsorted, base3_df, validate_index=False)
lib.get_description(sym3_unsorted)
```

### Expected Results

The row_range from the get_description is
```
date_range=(datetime.datetime(2023, 11, 3, 0, 0, tzinfo=datetime.timezone.utc), datetime.datetime(2023, 11, 2, 0, 0, tzinfo=datetime.timezone.utc))
```

Either return the correct row_range or nothing. Returning data that is incorrect but feasible is best avoided.

### OS, Python Version and ArcticDB Version

ArcticDB==4.1.0
Pandas==1.5.3
Python==3.10.12

### Backend storage used

LMDB

### Additional Context

Running on Jupyter colab.
Found independently based on a verbal bug report from an end user.

**Comment by alexowens90** [comment]
The values returned here are really just the first and last timestamps in the index, which are available in the index key.
To compute the true date range for an unsorted index would involve reading all of the data keys and doing a full scan of all of the index values, which obviously isn't desirable in `get_description`, which should be a cheap operation.
I would advocate updating the docs to describe this behaviour better rather than changing the behaviour, and log a warning if the data is known to be unsorted.
We could also log a warning if the data is of unknown sortedness. However, this applies to basically all data inside Man Group since we introduced this concept relatively recently, so would become a barrier to adoption of the V2 API.

**Comment by alexowens90** [comment]
My plan for the returned `date_range` tuple in `NativeVersionStore.get_info` and `Library.get_description` (and batch versions thereof) is:

- int/row-range index - `(NaT, NaT)`
- timestamp index UNSORTED - `(NaT, NaT)`
- timestamp index DESCENDING - either `(first_index_value, last_index_value)` or `(last_index_value, first_index_value)`, depending on consultation with current users
- timestamp index ASCENDING/UNKNOWN - `(first_index_value, last_index_value)`. Treat UNKNOWN like ASCENDING as ascending data written with older clients will be `UNKNOWN`.
