### ISSUE TITLE
LMDB Windows: lib.delete(symbol) does not reduce file size on disk

### ISSUE THREAD

**Issue by jshentz** [man-group/ArcticDB#1218]
Using Windows ldb data store.

Similar to issue #517 but related to symbols.

When deleting a symbol from a library, the file size on disk does not reduce, even when no snapshots are referencing it.

API documentation under library method **delete** states: _This may not actually delete the underlying data if a snapshot still references the version. See snapshot for more detail._ However, on Windows at least the file size never seems to go down.

For example, a library contains five 200MB symbols will yield a local data file of size approx. 1GB. Deleting any or all of the symbols does not reduce the file size, it remains at 1GB. This leads to a bloated file size over time.

**Comment by IvoDD** [comment]
Thank you for reporting. I managed to reproduce the issue. Code to repro below.

This is could be due to how LMDB itself frees up storage to the file system but we'll investigate to see if we can make it better.

#### Create library
```
from arcticdb import Arctic
import numpy as np

ac = Arctic("lmdb:///tmp/test")
lib = ac.create_library("lib")
```

Size after creaton:
```
$ du -h /tmp/test/lib/
16K     /tmp/test/lib/
```

#### Write data
```
large_value = np.arange(100000000)
for i in range(5):
    lib.write_pickle(f"symbol_{i}", large_value)
```

Size after writing data:
```
$ du -h /tmp/test/lib/
2.1G    /tmp/test/lib/
```

#### Delete data
```
for i in range(5):
    lib.delete(f"symbol_{i}")
```

Size after deleting data:
```
$ du -h /tmp/test/lib/
2.1G    /tmp/test/lib/
```

**Comment by muhammadhamzasajjad** [comment]
Hi @jshentz , I reproduced the issue. Debugging showed that the underlying data is in fact deleted as stated in the API documentation. The fact that the file size does not shrink is due to how `LMDB` works. In summary, when the data is deleted, `LMDB` does not return the used space to the Operating System as this is an expensive operation and would require compaction. Instead, `LMDB` keeps all the space and reuses it for future write operations. Find more in the following links:
https://kb.symas.com/lmdb-database-file-sizes-and-memory-utilization.html#:~:text=As%20database%20entries,by%20the%20OS
https://www.openldap.net/lists/openldap-devel/201505/msg00028.html

 In fact, continuing from the last step in the previous [comment ](https://github.com/man-group/ArcticDB/issues/1218#issuecomment-1889599898), we can show that the space is reused by `LMDB`:

**Size after deleting the data**:

```
$ du -h /tmp/test/lib/
2.1G    /tmp/test/lib/
```

**Write new data:**
```
large_value = np.arange(100000000)
for i in range(5, 10):
    lib.write_pickle(f"symbol_{i}", large_value)
```

**Size after writing 5 new symbols**:

```
$ du -h /tmp/test/lib/
2.2G    /tmp/test/lib/
```

Note that writing 5 symbols of the same size previously took `2.1G` of space. It only took `0.1G` new space to write 5 new symbols of the same size, hence reusing the space of deleted symbols.

**Comment by muhammadhamzasajjad** [comment]
In future, we could create a new feature in ArcticDB to perform compaction if memory efficiency is chosen by the user.

**Comment by jshentz** [comment]
Hi @muhammadhamzasajjad, thank you for the update. Understood, and makes sense. The enhancement (#1267) you've suggested would be a great feature which we could be run at quieter times, if required.
