### ISSUE TITLE
maint: Support protobuf Python library v5

### ISSUE THREAD

**Issue by poodlewars** [man-group/ArcticDB#1422]
**Is your feature request related to a problem? Please describe.**
Protobuf has released version 5 but we only support version 3 and 4. PR #1421 has constrained protobuf version for now.

We should relax this constraint that we are imposing on user's envs.

Our proto handling is quite complex - we compile Python proto stubs suitable for both proto 3 and proto 4 and choose which a user will "see" at runtime based on their installed proto version.

The solution should consider both wheels and Conda builds.

**Comment by jjerphan** [comment]
Currently ArcticDB's conda packages are built for:
 - [protobuf 4 on `main`](https://github.com/conda-forge/arcticdb-feedstock/blob/7e76263dcdbc643c6b1cffab694cad0c0582144e/recipe/meta.yaml#L37) since there are less constraints and to follow the ecosystem's releases
 - protobuf 3 for all the other branches to do environment contraints, see [the specification for `libevent-2.1.10`'s](https://github.com/conda-forge/arcticdb-feedstock/blob/851615398578517114dea63a9181783e1822c908/recipe/meta.yaml#L33) for instance

protobuf 5 has not yet been published on conda-forge. https://github.com/conda-forge/libprotobuf-feedstock/pull/213 is the first PR to start this work.

We might need to define a [build variant](https://docs.conda.io/projects/conda-build/en/stable/resources/variants.html) for protobuf 3, 4, and 5 once this last version is supported.

**Comment by jjerphan** [comment]
Related https://github.com/grpc/grpc/issues/36142.

**Comment by rhoens** [comment]
Hi, any movement on this? Just curious if there's a timeline

**Comment by jjerphan** [comment]
Likely addressed for conda-forge's builds once https://github.com/conda-forge/protobuf-feedstock/pull/216 is completed.

**Comment by jjerphan** [comment]
FYI https://github.com/conda-forge/protobuf-feedstock/pull/215 can also be watched (it was started before the bot opened https://github.com/conda-forge/protobuf-feedstock/pull/216).

**Comment by jjerphan** [comment]
ArcticDB can be build for `libprotobuf 5` on the feedstock: https://github.com/conda-forge/arcticdb-feedstock/pull/298

**Comment by jjerphan** [comment]
See: https://github.com/conda-forge/arcticdb-feedstock/pull/307
