### ISSUE TITLE
Shared memory support in ArcticDB

### ISSUE THREAD

**Issue by Hemansh31** [man-group/ArcticDB#1498]
**Is your feature request related to a problem? Please describe.**
We have a use case where we want to operate on large panda dataframes through multiprocessing and file based storage is giving us a bottleneck, since memory based storage is faster than disk, is it possible to add support for shared memory based storage in arcticdb

**Comment by poodlewars** [comment]
Hi @Hemansh31 we've done some testing with LMDB over a tmpfs, see the guide [here](https://docs.arcticdb.io/latest/tutorials/lmdb_and_in_memory/).

I think that it should still work if you just create an LMDB instance on a `/dev/shm` path rather than mounting a whole new tmpfs.

Let us know how you get on with it.
