### ISSUE TITLE
ArcticDB write_pickle issue with plain Python list

### ISSUE THREAD

**Issue by pwklein** [man-group/ArcticDB#240]
### Description:

When trying to use `write_pickle` with a plain Python list, ArcticDB throws an "OSError: [Errno 12] Cannot allocate memory" error. However, when using a NumPy array, the issue does not occur.

### Steps to reproduce:

1. Set up the environment with the following `pyproject.toml` dependencies:
   ```toml
   [tool.poetry.dependencies]
   python = "^3.10"
   arcticdb = "^1.0.1"
   numpy = "^1.24.2"
   pandas = "^2.0.0"

2. execute the following code after initialising arctic:

`lib.write_pickle("symbol", [1, 2, 3])`
(does not work)

`lib.write_pickle("symbol", np.array([1, 2, 3]))`
(does work)

**Comment by qc00** [comment]
Due to a recent change, please make sure you can allocate 4GB of virtual memory for `write_pickle`.

By this I mean there must be 4GB physical RAM + swap remaining at the time of the call.

The code is not going to use all 4GB, but it needs to be able to allocate that much address space to buffer the pickle.

**Comment by pwklein** [comment]
Thanks @qc00, that was it.
