### ISSUE TITLE
Parallelise across symbol for `read_batch` when `QueryBuilder` is used

### ISSUE THREAD

**Issue by GemDot** [man-group/ArcticDB#241]
**Is your feature request related to a problem? Please describe.**

`read_batch` is parallelized across symbols only when `QueryBuilder` is not used.

**Describe the solution you'd like**

`read_batch` should be modified to be also parallelised across symbols when `QueryBuilder` is used.

**Describe alternatives you've considered**

**Additional context**

We already apply within-symbol parallelisation so reading many large symbols will not see a significant performance boost with this work.

**Comment by willdealtry** [comment]
N.B. this caused a performance regression when we moved the batch methods from usign async_read_dataframe to read_dataframe_impl (necessary because the latter includes both the code path to directly read a dataframe and to pass it into the processing pipeline). The intention is to enqueue all the parallel operations up-front, which will mean that all read and write operations can be trivially parallelized - initially just the methods required to correct the performance regression, but this is also intended to be the general pattern goign forward.

**Comment by alexowens90** [comment]
Duplicates #1895
