### ISSUE TITLE
very slow to list symbols - no documentation around `list_symbol` caching

### ISSUE THREAD

**Issue by RockScience** [man-group/ArcticDB#392]
I have tried to stress test ArcticDB and have created >1000 symbols in the same library.
Now when I try to list the symbols in the library it takes between 1 and 2 minutes which is rather slow.
is that the expected behavior?

**Platform Information:**
 - OS (Including Linux Distribution): 18.04.1-Ubuntu
 - Python Version: 3.7.16 (default, Dec  7 2022, 01:12:19) [GCC 9.4.0]
 - ArcticDB ~~Version: 1.0.1~~ Edit: same issue using 1.2.0 (logs below this version)
 - Backend storage used:  Google S3

**Comment by mehertz** [comment]
Hi @RockScience. After calling `list_symbols` once, additional metadata is stored that should make future invocations of `list_symbols` faster. Our documentation is lacking in this unfortunately - I'll create a ticket to add more infformation about this mechanic.

Long story short though, your next call of `list_symbols` should be much faster. Give it a try and let me know!

**Comment by RockScience** [comment]
unfortunately we dont see significant change after triggering the function a second or third time. Around 1.7minutes to list 1400 synbols.
Is the cache in the client's environment or in the bucket itself?

**Comment by qc00** [comment]
It's stored in the bucket.

Could you run `arcticdb.config.set_log_level("INFO", {'version': "DEBUG", 'storage': "DEBUG"})`
and then give us the logs for `list_symbols()`?

**Comment by RockScience** [comment]
sorry I cannot run the first line, 

`NameError: name 'arcticdb' is not defined`

**Comment by qc00** [comment]
Yeah, you will need to `import arcticdb` first

**Comment by qc00** [comment]
Thanks! This is very helpful.

It took over a minute each time to list the symbol list keys from storage, and since we have to do it twice for consistency, the whole function is dominated by this.

The default page size for the list operation is 1000, so each one of the `Received object list` is 1000 keys. I don't know how many lines there are, but it seems to be 3-4 a second, so 250-300k keys in total, which is way larger than what we designed this cache to hold.

We compact these cache keys into a larger key each time `list_symbols` is called, so the most likely cause for the huge number of keys is because `list_symbols` is called infrequently.

I will have to discuss with my colleagues about potential improvements.

**Comment by RockScience** [comment]
thank you. In case that helps note that this log is after I called `list_symbols` twice within 10 min.

**Comment by qc00** [comment]
In this case, there's most likely a bug in the current release which failed to delete the cache keys after compaction.

We have rewritten part of this logic (#393), hopefully addressing this problem. I'll keep you updated.

**Comment by mehertz** [comment]
Hi @RockScience. #393 has been merged. Furthermore, #489 adds additional logging to clarify if the symbol list cache is in an expected state.

I'm going to close this ticket therefore. Happy to re-open if needed.
