### ISSUE TITLE
read_batch should catch all exceptions from individual queries and return what data it can

### ISSUE THREAD

**Issue by alexowens90** [man-group/ArcticDB#612]
#531 covers missing version-style errors

This should extend that implementation to cover other errors, such as missing index keys, missing data keys, etc

**Comment by alexowens90** [comment]
> Could we do it in a way that makes it possible to distinguish between logical errors like symbol/version not existing and storage errors like network/auth/rate limiting?
> 
> This is quite critical if any user builds high-level logic that reacts to the existence of symbols (e.g. a caching system).

The errors are currently split out into:

- symbol/version doesn't exist
- key doesn't exist
- everything else

"everything else" can obviously be further subcategorised in future as we become more consistent with how different storages react to different categories of errors

**Comment by qc00** [comment]
I am thinking for "everything else", the exception should be made accessible to the caller somehow. 

Otherwise, if someone wants to write an auto-retry wrapper, they will never be able to know if there's any point in retrying at all...

In order to not change the API again, we can offer a `get_last_exceptions()` function that lists the exception for each request in the batch.
